name: my_mvvm_app
description: "Flutter assessment project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.2
  device_preview: ^1.1.0
  dio: ^5.2.1+1
  envied: ^0.3.0+3
  envied_generator: ^0.3.0+3
  flutter:
    sdk: flutter
  flutter_secure_storage: ^5.0.2
  get_it: ^7.6.0
  http: ^0.13.3
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  loader_overlay: ^2.3.0
  logger: ^1.4.0
  meta: ^1.9.1
  path_provider: ^2.0.15
  provider: ^6.0.1
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_flavorizr: ^2.1.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  very_good_analysis: ^5.0.0+1

# ================================================
#  FLAVORIZR SETUP
# ================================================
# If updating applicationId and bundleId, call this command
# fvm flutter pub run flutter_flavorizr -p ios:xcconfig,ios:buildTargets,ios:schema,ios:plist,android:buildGradle

# If updating app icons, call this command 
# fvm flutter pub run flutter_flavorizr -p ios:icons,android:icons
flavorizr:
  flavors:
    production:
      app:
        name: "Flutter MVVM Project"
        icon: "assets/app_icons/prod_icon.png"

      android:
        applicationId: "com.example.mymvvmapp"

      ios:
        bundleId: "com.example.mymvvmapp"

    development:
      app:
        name: "[DEV] Flutter MVVM Project"
        icon: "assets/app_icons/dev_icon.png"

      android:
        applicationId: "com.example.mymvvmapp.development"

      ios:
        bundleId: "com.example.mymvvmapp.development"

    staging:
      app:
        name: "[STA] Flutter MVVM Project"
        icon: "assets/app_icons/staging_icon.png"

      android:
        applicationId: "com.example.mymvvmapp.staging"

      ios:
        bundleId: "com.example.mymvvmapp.staging"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family:  Mulish
      fonts:
        - asset: assets/fonts/mulish/Mulish-Black.ttf
          weight: 900
        - asset: assets/fonts/mulish/Mulish-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/mulish/Mulish-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/mulish/Mulish-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/mulish/Mulish-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/mulish/Mulish-Italic.ttf
          style: italic
        - asset: assets/fonts/mulish/Mulish-Light.ttf
          weight: 300
        - asset: assets/fonts/mulish/Mulish-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/mulish/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/mulish/Mulish-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/mulish/Mulish-Regular.ttf
        - asset: assets/fonts/mulish/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/mulish/Mulish-SemiBoldItalic.ttf
          weight: 600
          style: italic
